In [1]:
from collections import Counter
import pandas
documents = {
    'l1': "it was the best of times",
    'l2': "it was the worst of times",
    'l3': "it was the age of wisdom",
    'l4': "it was the age of foolishness"
}

all_words = ' '.join([documents[key] for key in documents.keys()])
documents['all'] = all_words

In [2]:
bigrams = set([b for l in documents.values() for b in zip(l.split(" ")[:-1], l.split(" ")[1:])])
bigrams = [' '.join(x) for x in bigrams]

In [3]:
l1_multi_hot = [1 if w in documents['l1'] else 0 for w in bigrams]
l2_multi_hot = [1 if w in documents['l2'] else 0 for w in bigrams]
l3_multi_hot = [1 if w in documents['l3'] else 0 for w in bigrams]
l4_multi_hot = [1 if w in documents['l4'] else 0 for w in bigrams]
all_multi_hot = [1 if w in documents['all'] else 0 for w in bigrams]

In [4]:
X = [l1_multi_hot, l2_multi_hot, l3_multi_hot, l4_multi_hot, all_multi_hot]
df = pandas.DataFrame(X, columns=list(bigrams))
df.T.rename(columns={0:'l1',1:'l2',2:'l3',3:'l4',4:'all'})

                l1  l2  l3  l4  all
times it         0   0   0   0    1
of foolishness   0   0   0   1    1
the worst        0   1   0   0    1
of times         1   1   0   0    1
the best         1   0   0   0    1
best of          1   0   0   0    1
of wisdom        0   0   1   0    1
foolishness it   0   0   0   0    1
it was           1   1   1   1    1
wisdom it        0   0   0   0    1
worst of         0   1   0   0    1
the age          0   0   1   1    1
was the          1   1   1   1    1
age of           0   0   1   1    1