<h1><center> Building a movie-recommender using the KNN </center></h1>

In [16]:
import pandas as pd
data = pd.read_csv('./movies_recommendation_data.csv', delimiter = ',')

In [17]:
data

,Movie ID,Movie Name,IMDB Rating,Biography,Drama,Thriller,Comedy,Crime,Mystery,History,Label
0,58,The Imitation Game,8.0,1,1,1,0,0,0,0,0
1,8,Ex Machina,7.7,0,1,0,0,0,1,0,0
2,46,A Beautiful Mind,8.2,1,1,0,0,0,0,0,0
3,62,Good Will Hunting,8.3,0,1,0,0,0,0,0,0
4,97,Forrest Gump,8.8,0,1,0,0,0,0,0,0
5,98,21,6.8,0,1,0,0,1,0,1,0
6,31,Gifted,7.6,0,1,0,0,0,0,0,0
7,3,Travelling Salesman,5.9,0,1,0,0,0,1,0,0
8,51,Avatar,7.9,0,0,0,0,0,0,0,0
9,47,The Karate Kid,7.2,0,1,0,0,0,0,0,0
10,50,A Brilliant Young Mind,7.2,0,1,0,0,0,0,0,0
11,49,A Time To Kill,7.4,0,1,1,0,1,0,0,0
12,30,Interstellar,8.6,0,1,0,0,0,0,0,0
13,94,The Wolf of Wall Street,8.2,1,0,0,1,1,0,0,0
14,6,Black Panther,7.4,0,0,0,0,0,0,0,0
15,73,Inception,8.8,0,0,0,0,0,0,0,0
16,44,The Wind Rises,7.8,1,1,0,0,0,0,0,0
17,65,Spirited Away,8.6,0,0,0,0,0,0,0,0
18,48,Finding Forrester,7.3,0,1,0,0,0,0,0,0
19,27,The Fountain,7.3,0,0,0,0,0,0,0,0
20,57,The DaVinci Code,6.6,0,0,1,0,0,1,0,0
21,57,Stand and Deliver,7.3,0,1,0,0,0,0,0,0
22,14,The Terminator,8.0,0,0,0,0,0,0,0,0
23,69,21 Jump Street,7.2,0,0,0,1,1,0,0,0
24,98,The Avengers,8.1,0,0,0,0,0,0,0,0
25,17,Thor: Ragnarok,7.9,0,0,0,1,0,0,0,0
26,12,Spirit: Stallion of the Cimarron,7.1,0,0,0,0,0,0,0,0
27,1,Hacksaw Ridge,8.2,1,1,0,0,0,0,1,0
28,86,12 Years a Slave,8.1,1,1,0,0,0,0,1,0
29,46,Queen of Katwe,7.4,1,1,0,0,0,0,0,0

### Problem Statement: Recommend 5 movies from this list most similar to "The Post"

The feature space of The Post looks as follows:
The Post:
IMDB Rating: 7.2; "Yes" to being a Biography,Drama, Thriller and Historical; "No" to being a Comedy/Crime/Mystery; So, kinda like this:

In [18]:
the_post = [7.2, 1, 1, 0, 0, 0, 0, 1, 0]

### The algorithm:

Part 1: Finding the Neighbors;
1. Calculate the distance between the query example and the current example from the data.<br>
2. Add the distance and the index of the example to an ordered collection<br>
3. Sort the ordered collection of distances and indices from smallest to largest (in ascending order) by the distances<br>

(If you’re feeling particularly fancy today, how about implementing a kd-tree or any other method of finding neighbors that you prefer!)<br>

Part 2: Performing the classification/regression;
1. Pick the first K entries from the sorted collection<br>
2. Get the labels of the selected K entries<br>
3. If regression, return the mean of the K labels<br> 
(If classification, return the mode of the K labels)<br>



... so here's a function to begin with....  <br>

<h4>Function inputs: </h4> <br>
data: is the data above!<br>
query: *the_post* is a good starting query<br>
k: no of neighbors you'd like to set<br>
distance_fn: preferred distance measure<br>
choice_fn: preferred statistic (mean/mode/median/etc)<br>


<h4>Function should return: </h4> <br>

The k nearest distances and indices to the query data point; the mean(or preferred statistic) of the labels of the neighbors!

In [ ]:
def knn(data, query, k, distance_fn, choice_fn):
    
    
    
    
    return k_nearest_distances_and_indices , choice_fn(k_nearest_labels)

In [ ]:
def euclidean_distance(a,b):
    return distance

<h3>We're now ready to recommend some movies! </h3>

In [ ]:
def recommend_movies(movie_query, k_recommendations):
    
    
    
    
    return movie_recommendations

(Scroll down for a sample implementation of the above!)

### Sample solution: https://towardsdatascience.com/machine-learning-basics-with-the-k-nearest-neighbors-algorithm-6a6e71d01761

In [7]:
from collections import Counter
import math

def knn(data, query, k, distance_fn, choice_fn):
    neighbor_distances_and_indices = []
    
    # 3. For each example in the data
    for index, example in enumerate(data):
        # 3.1 Calculate the distance between the query example and the current
        # example from the data.
        distance = distance_fn(example[:-1], query)
        
        # 3.2 Add the distance and the index of the example to an ordered collection
        neighbor_distances_and_indices.append((distance, index))
    
    # 4. Sort the ordered collection of distances and indices from
    # smallest to largest (in ascending order) by the distances
    sorted_neighbor_distances_and_indices = sorted(neighbor_distances_and_indices)
    
    # 5. Pick the first K entries from the sorted collection
    k_nearest_distances_and_indices = sorted_neighbor_distances_and_indices[:k]
    
    # 6. Get the labels of the selected K entries
    k_nearest_labels = [data[i][1] for distance, i in k_nearest_distances_and_indices]

    # 7. If regression (choice_fn = mean), return the average of the K labels
    # 8. If classification (choice_fn = mode), return the mode of the K labels
    return k_nearest_distances_and_indices , choice_fn(k_nearest_labels)

def mean(labels):
    return sum(labels) / len(labels)

def mode(labels):
    return Counter(labels).most_common(1)[0][0]

def euclidean_distance(point1, point2):
    sum_squared_distance = 0
    for i in range(len(point1)):
        sum_squared_distance += math.pow(point1[i] - point2[i], 2)
    return math.sqrt(sum_squared_distance)

def main():
    '''
    # Regression Data
    # 
    # Column 0: height (inches)
    # Column 1: weight (pounds)
    '''
    reg_data = [
       [65.75, 112.99],
       [71.52, 136.49],
       [69.40, 153.03],
       [68.22, 142.34],
       [67.79, 144.30],
       [68.70, 123.30],
       [69.80, 141.49],
       [70.01, 136.46],
       [67.90, 112.37],
       [66.49, 127.45],
    ]
    
    # Question:
    # Given the data we have, what's the best-guess at someone's weight if they are 60 inches tall?
    reg_query = [60]
    reg_k_nearest_neighbors, reg_prediction = knn(
        reg_data, reg_query, k=3, distance_fn=euclidean_distance, choice_fn=mean
    )
    
    '''
    # Classification Data
    # 
    # Column 0: age
    # Column 1: likes pineapple
    '''
    clf_data = [
       [22, 1],
       [23, 1],
       [21, 1],
       [18, 1],
       [19, 1],
       [25, 0],
       [27, 0],
       [29, 0],
       [31, 0],
       [45, 0],
    ]
    # Question:
    # Given the data we have, does a 33 year old like pineapples on their pizza?
    clf_query = [33]
    clf_k_nearest_neighbors, clf_prediction = knn(
        clf_data, clf_query, k=3, distance_fn=euclidean_distance, choice_fn=mode
    )

if __name__ == '__main__':
    main()

In [6]:


def recommend_movies(movie_query, k_recommendations):
    raw_movies_data = []
    with open('./group1/movies_recommendation_data.csv', 'r') as md:
        # Discard the first line (headings)
        next(md)

        # Read the data into memory
        for line in md.readlines():
            data_row = line.strip().split(',')
            raw_movies_data.append(data_row)

    # Prepare the data for use in the knn algorithm by picking
    # the relevant columns and converting the numeric columns
    # to numbers since they were read in as strings
    movies_recommendation_data = []
    for row in raw_movies_data:
        data_row = list(map(float, row[2:]))
        movies_recommendation_data.append(data_row)

    # Use the KNN algorithm to get the 5 movies that are most
    # similar to The Post.
    recommendation_indices, _ = knn(
        movies_recommendation_data, movie_query, k=k_recommendations,
        distance_fn=euclidean_distance, choice_fn=lambda x: None
    )

    movie_recommendations = []
    for _, index in recommendation_indices:
        movie_recommendations.append(raw_movies_data[index])

    return movie_recommendations

if __name__ == '__main__':
    the_post = [7.2, 1, 1, 0, 0, 0, 0, 1, 0] # feature vector for The Post
    recommended_movies = recommend_movies(movie_query=the_post, k_recommendations=5)

    # Print recommended movie titles
    for recommendation in recommended_movies:
        print(recommendation[1])

12 Years a Slave
Hacksaw Ridge
Queen of Katwe
The Wind Rises
A Beautiful Mind